language: node_js
node_js:
  - 15
cache:
  npm: true
install:
  - npm install
script:
  - npm test
  - npm run ebook:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ebook/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: main
branches:
  only:
    - main
after_success:
  - bash <(curl -s https://codecov.io/bash)
